on:
  push:
    branches:
      - main
      - dev/*
      - release/*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: run a oneline script
        run: echo hello world !!
