on:
  workflow_dispatch:
    
jobs:
  callworkflow:
          
    uses: ./.github/workflows/workflowcall.yml
    with:
      username: 'hellop'
      
  job2:
    runs-on: ubuntu-latest
    needs: callworkflow
    steps:
      - run: echo ${{ needs.callworkflow.outputs.firstword }} ${{ needs.callworkflow.outputs.secondword }}
    
