on: workflow_dispatch
jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this job will run first"
  fanout1:
    runs-on: ubuntu-latest
    needs: initial
    steps:
      - run: echo "this job will run after the initial job, in parallel with fanout2"
  fanout2:
    runs-on: ubuntu-latest
    needs: initial
    steps:
      - run: echo "this job will run after the initial job, in parallel with fanout1"
  fanout3:
    runs-on: ubuntu-latest
    needs: [fanout1, fanout2]
    steps:
      - run: echo "this job will run after fanout1 and 2 have finished running"
 
    
