name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: testenv
      url: https://github.com
    steps:
      - name: deploy
        # ...deployment-specific steps1
        env:
          super_secret: ${{secrets.ENVNAME}}
        run: echo $super_secret
          
