name: Deployment

on: workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: testenv
      url: https://github.com
    steps:
      - name: deploy
        # ...deployment-specific steps1
        env:
          super_secret: ${{ secrets.ENVNAME }}
        #run: echo super_secret 
        if: ${{env.super_secret == 'value2'}}
        run: echo 'true'
        
          
