name: Environments and Secrets serco

on:
 
  workflow_dispatch:
      
# Limit the permissions of the GITHUB_TOKEN
permissions:
  contents: read
  actions: read
  deployments: read

env:
  PROD_URL: 'https://github.com'
  DOCS_URL: 'https://docs.github.com'
  DEV_URL:  'https://docs.github.com/en/developers'

jobs:
  
  use-environment-dev:
    name: Use DEV environment
    runs-on: ubuntu-latest
    
    environment:
      name: DEV
      url: ${{ env.DEV_URL }}
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo env secret is redacted in the logs
        run: |
          echo Env secret is ${{ secrets.MY_ENV_SECRET }}
          echo ${{ secrets.MY_ENV_SECRET }} | sed 's/./& /g'
          
  
  
          
  
