name: envsecretsercodemo

on:
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: sercodemo
      url: https://github.com
    steps:
      - name: deploy
        env:
          super_secret: ${{ secrets.ENVNAME }}
          
        #if: ${{ env.super_secret == 'sercosecret' }}
        run: echo env.super_secret
         
