on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.KEYVAULTSECRET }}    
        enable-AzPSSession: true
    - uses: Azure/get-keyvault-secrets@v1.0
      id: azurekeyvault
      with:
        keyvault: "kv-gwu72je4akl7g"
        secrets: "AZURE-COSMOS-CONNECTION-STRING"          
    - name: Use Secret
      run: echo "My secret is ${{ steps.secrets.outputs.SecretName1 }}"
    
