on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.KEYVAULTSECRET }}    
        enable-AzPSSession: true
    - name: Retrieve secret from Key Vault    
      uses: azure/CLI@v1
      with:
        inlineScript: |
          secretValue=$(az keyvault secret show --vault-name kv-gwu72je4akl7g --name AZURE-COSMOS-CONNECTION-STRING --query value --output tsv)
          echo "SECRET_VALUE=$secretValue" >> $GITHUB_ENV
    - name: Use Secret
      run: echo "My secret is $SECRET_VALUE"

    - uses: Azure/get-keyvault-secrets@v1.0
      id: azurekeyvault
      with:
        keyvault: "kv-gwu72je4akl7g"
        secrets: "AZURE-COSMOS-CONNECTION-STRING"          
    - name: Use Secret
      run: echo "My secret is ${{ steps.secrets.outputs.SecretName1 }}"
    
