on:
  workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo " the job was triggered by ${{ github.event_name }} event"
      - run: echo " the job is ruuning on ${{ runner.os }} server hosted by github"
      - run: echo " the name of the branch ${{ github.ref }} and your repository is ${{ github.repository }}"
      - name: adding markdown
        run: echo "hello world ! :rocket:" >> $GITHUB_STEP_SUMMARY
      
