name: reposecret

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: deploy
        # ...deployment-specific steps1
        with:
          super_secret: ${{ secrets.REPODEMOSECRET }}
        
        if: ${{env.super_secret == 'repodemosecret'}}
        run: echo 'true'
