name: reposecret

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: deploy             
        with: # Set Azure credentials secret as an input
          credentials: ${{ secrets.repodemosecret }}
        
        if: ${{secrets.repodemosecret == 'repodemosecret'}}
          echo "flag=true"
        
