name: reposecret

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: deploy             
        if: ${{secrets.repodemosecret == 'repodemosecret'}}
          echo "flag=true"
        
        
        
