on:
  workflow_call:
    inputs:
      username:
        description: 'username passed from workflow'
        default: 'jon'
        required: false
        type: string
jobs:
  printusername:
    runs-on: ubuntu-latest
    steps:
      - name: print name
        run: echo username ${{ inputs.username }}
