on:
  workflow_call:
    inputs:
      username:
        description: 'username from caller workflow'
        default: 'jon'
        required: false
        type: string
    outputs:
      firstword:
        description: 'first output string'
        value: ${{ jobs.print-username.outputs.output1 }}
      secondword:
        description: 'second output string'
        value: ${{ jobs.print-username.outputs.output2 }}
        
jobs:
  print-username:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
       - id: step1
         run: echo "firstword=hello" >> $GITHUB_OUTPUT
       - id: step2
         run: echo "secondword=world" >> $GITHUB_OUTPUT
