on: workflow_dispatch
env:
  DAY_OF_WEEK: Monday
jobs:
  greetinjob:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name : "Say hello its monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK"
        env:
          First_Name: Mona
